---
- name: Reset User password
  hosts: all
  become: true

  tasks:
    # Reset user password to Temp99! & update servicenow ticket & close servicenow ticket
    - name: Reset user password to Temp99!
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        password: "{{ _password_ }}"

    - name: Update servicenow ticket
      servicenow.itsm.ticket:
        sys_id: "{{ sys_id }}"
        state: new
        type: problem
        priority: low
        impact: low
        attachments:
          - path: /home/ano-user/Downloads/test.txt
        description: "{{ description }}"

    - name: Close servicenow ticket
      servicenow.itsm.ticket:
        sys_id: "{{ sys_id }}"
        state: closed
        resolution: fixed
        resolution_code: fix_applied
        description: "{{ description }}"
    
