---
- name: Add firewall rules
  hosts: all
  become: true

  tasks:
  - name: Add firewall rules
    ansible.posix.firewalld:
      port: "{{ item }}"
      permanent: true
      state: enabled
      immediate: true