---
- name: Add firewall rules
  hosts: all
  become: true

  tasks:
  - name: Add firewall rules
    ansible.posix.firewalld:
      port: "{{ item }}"
      permanent: true
      state: enabled
      immediate: true
    loop:
      - 80
      - 443
      - 22
      - 53
      - 1025
      - 1026
      - 1027
      - 1028
      - 1029
      - 1030
      - 1031
      - 1032
      - 1033
      - 1034
      - 1035
      - 1036
      - 1037
      - 1038
      - 1039
      - 1040
      - 1041
      - 1042
      - 1043
      - 1044
      - 1045
      - 1046
      - 1047
      - 1048
      - 1049
      - 1050
      - 1051
      - 1052
      - 1053
      -
  